{% set name = "ffnvcodec-headers" %}
{% set version = "12.2.72.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FFmpeg/nv-codec-headers/releases/download/n{{ version }}/nv-codec-headers-{{ version }}.tar.gz
  sha256: c295a2ba8a06434d4bdc5c2208f8a825285210d71d91d572329b2c51fd0d4d03

build:
  number: 0
  skip: true  # [osx]
  script: make PREFIX=${PREFIX} install  # [unix]
  script: make PREFIX=%LIBRARY_PREFIX% install  # [win]

requirements:
  build:
    - autotools_clang_conda  # [win]
    - m2-sed                 # [win]
    - make
    # Otherwise the PREFIX doesn't seem to be correctly setup for windows
    # - {{ compiler('c') }}

test:
  commands:
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_cuda.h       # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_cuviddec.h   # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_loader.h     # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_nvcuvid.h    # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/nvEncodeAPI.h        # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/ffnvcodec.pc             # [unix]
    - if not exist %PREFIX%\\Library\\include\\ffnvcodec\\dynlink_cuda.h exit 1      # [win]
    - if not exist %PREFIX%\\Library\\include\\ffnvcodec\\dynlink_cuviddec.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\ffnvcodec\\dynlink_loader.h exit 1    # [win]
    - if not exist %PREFIX%\\Library\\include\\ffnvcodec\\dynlink_nvcuvid.h exit 1   # [win]
    - if not exist %PREFIX%\\Library\\include\\ffnvcodec\\nvEncodeAPI.h exit 1       # [win]
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\ffnvcodec.pc exit 1            # [win]

about:
  home: https://git.videolan.org/?p=ffmpeg/nv-codec-headers.git
  license: MIT
  license_file: LICENSE
  summary: FFmpeg version of headers required to interface with Nvidias codec APIs
  description: |
    Corresponds to Video Codec SDK version 11.1.5.

    Minimum required driver versions:
    Linux: 470.57.02 or newer
    Windows: 471.41 or newer

extra:
  recipe-maintainers:
    - hmaarrfk
    - sdvillal
